apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-migration
  labels:
    app: liquibase-migration
spec:
  template:
    metadata:
      labels:
        app: liquibase-migration
    spec:
      restartPolicy: OnFailure
      containers:
        - name: liquibase
          image: liquibase/liquibase:4.18
          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache wget
              wget -O /liquibase/lib/postgresql.jar https://jdbc.postgresql.org/download/postgresql-42.6.0.jar
              find /liquibase -name "*.xml" -type f
              ls -la /liquibase/changelog/
              liquibase \
                --driver=org.postgresql.Driver \
                --classpath=/liquibase/lib/postgresql.jar \
                --url="jdbc:postgresql://postgres:5432/postgres" \
                --username=$DB_USERNAME \
                --password=$DB_PASSWORD \
                --searchPath=/liquibase/changelog \
                --changeLogFile=master.xml \
                update
          env:
            - name: DB_USERNAME
              value: "lab_user"
            - name: DB_PASSWORD
              value: "password"
          volumeMounts:
            - name: liquibase-changelog
              mountPath: /liquibase/changelog
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
      volumes:
        - name: liquibase-changelog
          configMap:
            name: liquibase-changelog
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: liquibase-changelog
data:
  master.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <databaseChangeLog
            xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
    http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.9.xsd">
        <changeSet id="1" author="lab_user">
            <sql>
                CREATE SCHEMA IF NOT EXISTS lab2var10;
                GRANT USAGE ON SCHEMA lab2var10 TO lab_user;
            </sql>
        </changeSet>
        <changeSet id="2" author="lab_user">
            <createTable tableName="categories" schemaName="lab2var10">
                <column name="id" type="SERIAL">
                    <constraints primaryKey="true" nullable="false"/>
                </column>
                <column name="name" type="VARCHAR(100)">
                    <constraints nullable="false" unique="true"/>
                </column>
            </createTable>
        </changeSet>
        <changeSet id="3" author="lab_user">
            <createTable tableName="products" schemaName="lab2var10">
                <column name="id" type="SERIAL">
                    <constraints primaryKey="true" nullable="false"/>
                </column>
                <column name="code" type="VARCHAR(50)">
                    <constraints nullable="false" unique="true"/>
                </column>
                <column name="name" type="VARCHAR(200)">
                    <constraints nullable="false"/>
                </column>
                <column name="category_id" type="INTEGER">
                    <constraints nullable="false"/>
                </column>
                <column name="manufacturer" type="VARCHAR(200)">
                    <constraints nullable="false"/>
                </column>
            </createTable>
            <addForeignKeyConstraint
                    baseTableSchemaName="lab2var10"
                    baseTableName="products"
                    baseColumnNames="category_id"
                    constraintName="fk_products_category"
                    referencedTableSchemaName="lab2var10"
                    referencedTableName="categories"
                    referencedColumnNames="id"
                    onDelete="CASCADE"/>
        </changeSet>
        <changeSet id="4" author="lab_user">
            <createTable tableName="customers" schemaName="lab2var10">
                <column name="id" type="SERIAL">
                    <constraints primaryKey="true" nullable="false"/>
                </column>
                <column name="name" type="VARCHAR(200)">
                    <constraints nullable="false"/>
                </column>
                <column name="address" type="VARCHAR(300)">
                    <constraints nullable="false"/>
                </column>
                <column name="is_legal_entity" type="BOOLEAN">
                    <constraints nullable="false"/>
                </column>
                <column name="document_number" type="VARCHAR(100)"/>
                <column name="document_series" type="VARCHAR(50)"/>
                <column name="bank_name" type="VARCHAR(200)"/>
                <column name="bank_account" type="VARCHAR(100)"/>
            </createTable>
        </changeSet>
        <changeSet id="5" author="lab_user">
            <createTable tableName="regions" schemaName="lab2var10">
                <column name="id" type="SERIAL">
                    <constraints primaryKey="true" nullable="false"/>
                </column>
                <column name="name" type="VARCHAR(100)">
                    <constraints nullable="false" unique="true"/>
                </column>
                <column name="country" type="VARCHAR(100)">
                    <constraints nullable="false"/>
                </column>
            </createTable>
        </changeSet>
        <changeSet id="6" author="lab_user">
            <createTable tableName="settlements" schemaName="lab2var10">
                <column name="id" type="SERIAL">
                    <constraints primaryKey="true" nullable="false"/>
                </column>
                <column name="name" type="VARCHAR(100)">
                    <constraints nullable="false"/>
                </column>
                <column name="region_id" type="INTEGER">
                    <constraints nullable="false"/>
                </column>
            </createTable>
            <addForeignKeyConstraint
                    baseTableSchemaName="lab2var10"
                    baseTableName="settlements"
                    baseColumnNames="region_id"
                    constraintName="fk_settlements_region"
                    referencedTableSchemaName="lab2var10"
                    referencedTableName="regions"
                    referencedColumnNames="id"
                    onDelete="CASCADE"/>
        </changeSet>
        <changeSet id="7" author="lab_user">
            <createTable tableName="invoices" schemaName="lab2var10">
                <column name="id" type="SERIAL">
                    <constraints primaryKey="true" nullable="false"/>
                </column>
                <column name="invoice_date" type="DATE">
                    <constraints nullable="false" checkConstraint="invoice_date &lt;&#61; CURRENT_DATE"/>
                </column>
                <column name="customer_id" type="INTEGER">
                    <constraints nullable="false"/>
                </column>
                <column name="settlement_id" type="INTEGER">
                    <constraints nullable="false"/>
                </column>
                <column name="total_amount" type="DECIMAL(15,2)">
                    <constraints nullable="false"/>
                </column>
                <column name="enterprise" type="VARCHAR(200)">
                    <constraints nullable="false"/>
                </column>
            </createTable>
            <addForeignKeyConstraint
                    baseTableSchemaName="lab2var10"
                    baseTableName="invoices"
                    baseColumnNames="customer_id"
                    constraintName="fk_invoices_customer"
                    referencedTableSchemaName="lab2var10"
                    referencedTableName="customers"
                    referencedColumnNames="id"
                    onDelete="CASCADE"/>
            <addForeignKeyConstraint
                    baseTableSchemaName="lab2var10"
                    baseTableName="invoices"
                    baseColumnNames="settlement_id"
                    constraintName="fk_invoices_settlement"
                    referencedTableSchemaName="lab2var10"
                    referencedTableName="settlements"
                    referencedColumnNames="id"
                    onDelete="CASCADE"/>
        </changeSet>
        <changeSet id="8" author="lab_user">
            <createTable tableName="invoice_items" schemaName="lab2var10">
                <column name="id" type="SERIAL">
                    <constraints primaryKey="true" nullable="false"/>
                </column>
                <column name="invoice_id" type="INTEGER">
                    <constraints nullable="false"/>
                </column>
                <column name="product_id" type="INTEGER">
                    <constraints nullable="false"/>
                </column>
                <column name="quantity" type="INTEGER">
                    <constraints nullable="false" checkConstraint="quantity >= 0"/>
                </column>
                <column name="price" type="DECIMAL(15,2)">
                    <constraints nullable="false" checkConstraint="price >= 0"/>
                </column>
            </createTable>
            <addForeignKeyConstraint
                    baseTableSchemaName="lab2var10"
                    baseTableName="invoice_items"
                    baseColumnNames="invoice_id"
                    constraintName="fk_invoice_items_invoice"
                    referencedTableSchemaName="lab2var10"
                    referencedTableName="invoices"
                    referencedColumnNames="id"
                    onDelete="CASCADE"/>
            <addForeignKeyConstraint
                    baseTableSchemaName="lab2var10"
                    baseTableName="invoice_items"
                    baseColumnNames="product_id"
                    constraintName="fk_invoice_items_product"
                    referencedTableSchemaName="lab2var10"
                    referencedTableName="products"
                    referencedColumnNames="id"
                    onDelete="CASCADE"/>
        </changeSet>
        <changeSet id="9" author="lab_user">
            <createTable tableName="price_history" schemaName="lab2var10">
                <column name="id" type="SERIAL">
                    <constraints primaryKey="true" nullable="false"/>
                </column>
                <column name="product_id" type="INTEGER">
                    <constraints nullable="false"/>
                </column>
                <column name="change_date" type="DATE">
                    <constraints nullable="false" checkConstraint="change_date &lt;&#61; CURRENT_DATE"/>
                </column>
                <column name="price" type="DECIMAL(15,2)">
                    <constraints nullable="false" checkConstraint="price > 0"/>
                </column>
            </createTable>
            <addForeignKeyConstraint
                    baseTableSchemaName="lab2var10"
                    baseTableName="price_history"
                    baseColumnNames="product_id"
                    constraintName="fk_price_history_product"
                    referencedTableSchemaName="lab2var10"
                    referencedTableName="products"
                    referencedColumnNames="id"
                    onDelete="CASCADE"/>
        </changeSet>
        <changeSet id="10" author="lab_user">
            <createIndex indexName="idx_products_category" schemaName="lab2var10" tableName="products">
                <column name="category_id"/>
            </createIndex>
            <createIndex indexName="idx_products_code" schemaName="lab2var10" tableName="products">
                <column name="code"/>
            </createIndex>
            <createIndex indexName="idx_customers_legal" schemaName="lab2var10" tableName="customers">
                <column name="is_legal_entity"/>
            </createIndex>
            <createIndex indexName="idx_customers_name" schemaName="lab2var10" tableName="customers">
                <column name="name"/>
            </createIndex>
            <createIndex indexName="idx_regions_country" schemaName="lab2var10" tableName="regions">
                <column name="country"/>
            </createIndex>
            <createIndex indexName="idx_settlements_region" schemaName="lab2var10" tableName="settlements">
                <column name="region_id"/>
            </createIndex>
            <createIndex indexName="idx_invoices_date" schemaName="lab2var10" tableName="invoices">
                <column name="invoice_date"/>
            </createIndex>
            <createIndex indexName="idx_invoices_customer" schemaName="lab2var10" tableName="invoices">
                <column name="customer_id"/>
            </createIndex>
            <createIndex indexName="idx_invoices_settlement" schemaName="lab2var10" tableName="invoices">
                <column name="settlement_id"/>
            </createIndex>
            <createIndex indexName="idx_invoice_items_invoice" schemaName="lab2var10" tableName="invoice_items">
                <column name="invoice_id"/>
            </createIndex>
            <createIndex indexName="idx_invoice_items_product" schemaName="lab2var10" tableName="invoice_items">
                <column name="product_id"/>
            </createIndex>
            <createIndex indexName="idx_price_history_product" schemaName="lab2var10" tableName="price_history">
                <column name="product_id"/>
            </createIndex>
            <createIndex indexName="idx_price_history_date" schemaName="lab2var10" tableName="price_history">
                <column name="change_date"/>
            </createIndex>
        </changeSet>
        <changeSet id="11" author="lab_user">
            <sql>
                INSERT INTO lab2var10.categories (name) VALUES
                ('электроника'),
                ('одежда'),
                ('продукты питания'),
                ('книги'),
                ('мебель')
                ON CONFLICT (name) DO NOTHING;
                INSERT INTO lab2var10.products (code, name, category_id, manufacturer) VALUES
                ('el001', 'смартфон', 1, 'samsung'),
                ('el002', 'ноутбук', 1, 'lenovo'),
                ('cl001', 'футболка', 2, 'nike'),
                ('fd001', 'хлеб', 3, 'хлебзавод №1'),
                ('bk001', 'учебник sql', 4, 'питер')
                ON CONFLICT (code) DO NOTHING;
            </sql>
        </changeSet>
    </databaseChangeLog>
