apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-app
  labels:
    app: quarkus-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quarkus-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: quarkus-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: quarkus-app
      containers:
        - name: quarkus-app
          image: quarkus-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: QUARKUS_DATASOURCE_REACTIVE_URL
              value: "postgresql://postgres:5432/postgres"
            - name: QUARKUS_DATASOURCE_USERNAME
              value: "lab_user"
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: "password"
            - name: QUARKUS_HIBERNATE_REACTIVE_ENABLED
              value: "true"
            - name: QUARKUS_REDIS_HOSTS
              value: "redis://redis:6379"
            - name: APP_AUTH_USERNAME
              value: "admin"
            - name: APP_AUTH_PASSWORD
              value: "password"
          livenessProbe:
            httpGet:
              path: /public/health
              port: 8080
              httpHeaders:
                - name: Authorization
                  value: "Basic YWRtaW46cGFzc3dvcmQ="
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /public/health
              port: 8080
              httpHeaders:
                - name: Authorization
                  value: "Basic YWRtaW46cGFzc3dvcmQ="
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3